name: Format
on:
  pull_request:
    branches: [master]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Format
        run: |
          yarn install --frozen-lockfile
          yarn run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
